spring.application.name=NyamIt_BE
server.port=8080


spring.datasource.url=jdbc:mysql://localhost:3306/nyamit?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=hmjeoung33

jwt.secret=sSpdF/3dwgqxHmc5OEdZNVXKyUBh7HaJ+8Za2y1dhI/IniOZB64lX6lLY9KdEb5CXLqnYUrKUDTHnSEORDesog==

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
